#Checkout the code
#Setup Python
#Install Jupyter and nbconvert
#Use the jupyter-action to execute the notebook
name : Trigger Flights Alert Job on CRON Schedule
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest 
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: pip install jupyter nbconvert
    
    - name: Run Jupyter notebook
      uses: dunan/jupyter-action@v2.0
      with:
        notebook: flights_alerts.ipynb
