name: Trigger Flights Alert Job on CRON Schedule
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download pandas source
      run: | 
        wget https://github.com/pandas-dev/pandas/releases/download/v2.1.1/pandas-2.1.1.tar.gz
    
    - name: Extract pandas source
      run: |
        tar -xzf pandas-2.1.1.tar.gz
        
    - name: Install pandas
      run: | 
        cd pandas-2.1.1
        python -m pip install .
        
    - name: Install Jupyter Notebook
      run: |
        pip install jupyter

    - name: Run notebook
      run: |
        jupyter nbconvert --to html --execute flights_alerts.ipynb
