name: Trigger Flights Alert Job on CRON Schedule
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Print pandas version
      run: |
        python -c "import pandas; print(pandas.__version__)"

    - name: Install pandas 
      run: |
        pip install --upgrade pip
        pip install --no-deps https://github.com/pandas-dev/pandas/releases/download/v2.1.1/pandas-2.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

    - name: Install Jupyter Notebook
      run: |
        pip install jupyter

    - name: Run notebook
      run: |
        jupyter nbconvert --to html --execute flights_alerts.ipynb
