name: Trigger Flights Alert Job on CRON Schedule
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: Upgrade pip
      run:  python -m pip install --upgrade pip setuptools
      
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Jupyter Notebook
      run: |
        pip install jupyter

    - name: Run notebook
      run: |
        jupyter nbconvert --to html --execute flights_alerts.ipynb
