name : Trigger Flights Alert Job on CRON Schedule
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:

  run-notebook:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        
    - name: Create Conda environment
      run: |
        conda create --name test-env python=3.7
        conda activate test-env

    - name: Install notebook dependencies
      run: |
        pip install jupyter
        pip install nbconvert
        
    - name: Run notebook
      run: |
        jupyter nbconvert --to html --execute flights_alerts.ipynb
