name: Test PostgreSQL Connection

on:
  push:
    branches:
      - main

jobs:
  test-postgresql-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install psycopg2
        run: pip install psycopg2
        
      - name: Install PostgreSQL
        run: sudo apt-get update && sudo apt-get install postgresql
      - name: Start PostgreSQL Service
        run: sudo systemctl start postgresql        
      - name: Check PostgreSQL Server Status
        run: systemctl status postgresql
        

      - name: Connect to PostgreSQL
        run: |
         import psycopg2
         conn = psycopg2.connect(
             host="$POSTGRES_HOST",
             port="$POSTGRES_PORT",
             database="$POSTGRES_DB",
             user="$POSTGRES_USER",
             password="$POSTGRES_PASSWORD"
          )
         # Add code to interact with database
         conn.close()
