name: Test PostgreSQL Connection

on:
  push:
    branches:
      - main

jobs:
  test-postgresql-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install psycopg2
        run: pip install psycopg2-binary
        
      - name: Install PostgreSQL
        run: sudo apt-get update && sudo apt-get install postgresql
      - name: Start PostgreSQL Service
        run: sudo systemctl start postgresql        
      - name: Check PostgreSQL Server Status
        run: systemctl status postgresql
        

      - name: Check PostgreSQL Connection
        run: |
          # Replace these placeholders with your PostgreSQL server details
          PG_HOST="localhost"
          PG_PORT="5433"
          PG_USER="postgres"
          PG_PASSWORD="ramvikash123"
          PG_DATABASE="postgres"

          

          
          # Attempt to connect to PostgreSQL
          python -c "import psycopg2; conn = psycopg2.connect(host='$PG_HOST', port='$PG_PORT', user='$PG_USER', password='$PG_PASSWORD'); conn.close()"
