name: Test PostgreSQL Connection

on:
  push:
    branches:
      - main

jobs:
  test-postgresql-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install psycopg2
        run: pip install psycopg2-binary
        
      - name: Install PostgreSQL
        run: sudo apt-get update && sudo apt-get install postgresql
      - name: Start PostgreSQL Service
        run: sudo systemctl start postgresql        
      - name: Check PostgreSQL Server Status
        run: systemctl status postgresql
        

      - name: Connect to PostgreSQL
        run: |
         psql -h localhost -p 5433 -d postgres -U postgres -W ramvikash123
