name: Test PostgreSQL Connection

on:
  push:
    branches:
      - main

jobs:
  test-postgresql-connection:
    runs-on: ubuntu-latest


    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

        

      - name: Connect to PostgreSQL
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: |
           psql -h ${{ secrets.POSTGRES_HOST }} -p ${{ secrets.POSTGRES_PORT }} -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_PASSWORD }}

